# Author: crifan
# Date: 2012-05-16
#
# -----------------------------------------------------------------
#  generate output from DocBook sources
#  this is entry makefile for docbook
# -----------------------------------------------------------------
# run this makefile under src directory:
# [office]
# pwd = /home/CLi/develop/docbook/books/xxx/src
# [home]
# pwd = /cygdrive/e/Dev_Root/docbook/dev/books/xxx/src

################################################################################
# Project Settings
################################################################################

# also means main source file name
PROJECT_NAME = regular_expression
SUB_SRC_FILES = \
    ch01_reg_exp_common.xml \
    ch02_javascript_regexp.xml \
    ch03_npp_regular_expression.xml \
    ch04_python_re.xml \
    ch05_csharp_regex.xml \
    ch06_php_pcre.xml \
    ch07_perl_two_slash.xml \
    ch08_java_regex.xml \
    ch09_editplus_tr1.xml \
    ch10_ultraedit_regex.xml \
    ch11_actionscript_regexp.xml \
    ch12_objectc_regexkitLite.xml \
    ch13_reg_exp_compare.xml \
    reference.xml \

DOCBOOK_MAKEFILE_ROOT = ../../../config
################################################################################
# Include docbook makefile
################################################################################
include $(DOCBOOK_MAKEFILE_ROOT)/docbook.mk